# Generated by Django 2.0.3 on 2018-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='banner')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=30, verbose_name='标题')),
                ('name', models.CharField(max_length=30, verbose_name='站名')),
                ('copy_right', models.CharField(max_length=40, verbose_name='版权')),
            ],
        ),
        migrations.CreateModel(
            name='ImgGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name=False)),
            ],
        ),
    ]
