# Generated by Django 2.0.3 on 2018-08-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelateObjs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('abstract', models.CharField(max_length=140)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imggallery',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
