# Generated by Django 2.0.3 on 2018-08-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_auto_20180805_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='banner', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='imggallery',
            name='img',
            field=models.ImageField(upload_to='gallery', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='imggallery',
            name='update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='relateobjs',
            name='abstract',
            field=models.CharField(max_length=140, verbose_name='推荐摘要'),
        ),
        migrations.AlterField(
            model_name='relateobjs',
            name='title',
            field=models.CharField(max_length=30, verbose_name='推荐项'),
        ),
        migrations.AlterField(
            model_name='relateobjs',
            name='url',
            field=models.URLField(verbose_name='推荐URL'),
        ),
    ]
