# Generated by Django 2.0.3 on 2018-08-14 21:23

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_auto_20180814_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '站点导航图', 'verbose_name_plural': '站点导航图'},
        ),
        migrations.AlterModelOptions(
            name='cite',
            options={'verbose_name': '站点信息', 'verbose_name_plural': '站点信息'},
        ),
        migrations.AlterModelOptions(
            name='imggallery',
            options={'verbose_name': '图集', 'verbose_name_plural': '图集'},
        ),
        migrations.AlterModelOptions(
            name='relateobjs',
            options={'verbose_name': '推荐管理', 'verbose_name_plural': '推荐管理'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=stdimage.models.StdImageField(upload_to='banner', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='imggallery',
            name='img',
            field=stdimage.models.StdImageField(upload_to='gallery', verbose_name='图片'),
        ),
    ]
