# Generated by Django 2.0.3 on 2018-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180802_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(default='default.jpg', upload_to='blog_banner'),
            preserve_default=False,
        ),
    ]
