# Generated by Django 2.0.3 on 2018-08-09 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180806_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=True),
        ),
    ]
