# Generated by Django 2.0.3 on 2018-08-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180810_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='abstract',
            field=models.CharField(max_length=140, verbose_name='文章摘要'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(upload_to='blog_banner', verbose_name='文章导航图片'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='文章短链接'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='留言者邮箱'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='head_img',
            field=models.ImageField(upload_to='comment_user', verbose_name='留言者头像'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=30, verbose_name='留言者名'),
        ),
    ]
