# Generated by Django 2.0.3 on 2018-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='公司名')),
                ('address', models.CharField(max_length=30, verbose_name='公司地址')),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('git', models.URLField()),
                ('mission', models.TextField()),
                ('about', models.TextField()),
                ('support', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='service name')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='service',
            field=models.ManyToManyField(related_name='companies_of', to='user.Service'),
        ),
    ]
