# Generated by Django 2.0.3 on 2018-08-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180802_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.CharField(max_length=30, verbose_name='电话号'),
        ),
    ]
