# Generated by Django 2.0.3 on 2018-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180802_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='qq',
            field=models.CharField(default=674076193, max_length=20, verbose_name='QQ号'),
            preserve_default=False,
        ),
    ]
