# Generated by Django 2.0.3 on 2018-08-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_company_qq'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
