# Generated by Django 2.0.3 on 2018-08-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_service_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(verbose_name='关于我们'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='company',
            name='git',
            field=models.URLField(verbose_name='URL地址'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mission',
            field=models.TextField(verbose_name='职责'),
        ),
        migrations.AlterField(
            model_name='company',
            name='support',
            field=models.TextField(verbose_name='服务简介'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=30, verbose_name='服务项'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.URLField(verbose_name='URL示例地址'),
        ),
    ]
